### ISSUE TITLE
Make a compiled jar

### ISSUE THREAD

**Issue by on9chai** [Exortions/skyblock-2.0#153]
I had some problems while building the jar, could you just compile it for me?

**Comment by Exortions** [comment]
Yeah

**Comment by Exortions** [comment]
Here's the latest commit:
[skyblock-1.0.0.zip](https://github.com/Exortions/skyblock-2.0/files/10404339/skyblock-1.0.0.zip)
(It's a ZIP because GitHub doesn't support JARs)
