### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by iKiwo** [Exortions/skyblock-2.0#156]
Is the project complete?

**Comment by Exortions** [comment]
Uhhh yeah pretty much what @KingGamerXd said, this project is far from complete - we were only aiming to create everything before dungeons, but we are still a little off of that mark.

The biggest thing is all the bugs, so feel free to find and fix them 👍🏻

**Comment by Exortions** [comment]
Do whatever you want. Feel free to submit a pull request with your changes.
