### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by KingGamerXd** [Exortions/skyblock-2.0#159]
So i fully tested plugin and it all features and after that i found lot of bugs

Dragon ai : 
Dragon ai is bugged and very bad and if player die while dragon fight it break game and server

Crafting Table:
Shapeless recipes and normal vanilla recipes are bugged in crafting Gui

lot of nbts:
there are too much nbts in items which can cause lag and high resource usages

Mobs:
some time it spawn some bugged mobs which cant be killed

Slow database:
it use Yml for storing Playerdata which very slow and cause delay

delay on join event :
as it use yml to store so it causes lag and delay on playerjoin event

Server Crash:
if 3 player or more player join at same time so it crash server not matter how good resource you have i tried on 100gb ram server and good cpu but it still crash because of slow database

Mob system:
i noticed before loading mob system it use less ram and resource and after mob thing loaded it start using double ram and resources

Island System:
it create new island world for every new player which can cause lag and hard mange worlds you should add new island system which generate islands with space of 300 block like if player 1 like is on 0 100 0 then it should generate new island on 0 400 0 in same world instead of creating new world

Npc:
there are lot of npc which can cause lag should remove some npc or add region thing so it should spawn npc in player region only

Items:
player can place custom items like head and other things and after placing it became normal item there should a thing so if player by mistake place any custom head so he can break in and he should get that custom head istead of normal steve head

Minions:
if you stop server and then start again so it will replace minion with normal armor stand

Pets:
pet animation is little buggy

Accessory:
if you keep clicking on talisman in Accessory bag it will keep increasing your stats

 enchantment:
if you enchat any armor part it remove other stats tag form armor part this bug only happen for armor part but not for sword

Reforge:
Reforge is also little bug it not give all stats

these are bugs i found other things work fine and good i hope these bug get fixed btw Good Work 👍

**Comment by byteinjection** [comment]
Im planning to fix all known bugs of this system. As soon as i fixed all bugs, i will update this repository to the current skyblock system (dungeons, dungeon items, garden, etc)

**Comment by KingGamerXd** [comment]
I already fixed these all bugs and performance issue and made it runing at 600mb Ram and 20tps . but i cant push for some reasons

**Comment by Exortions** [comment]
Make a fork and push

**Comment by KingGamerXd** [comment]
I cant push fixed version because I removed lot of code and things like bazaar and minion as it was lot cauing issue and was not completed. I will soon again fix all of these bugs after exams and that time I wont remove anything. The code was also not clean so I will again start work on this project soon in few days after my exams finish.

**Comment by OptimusChen** [comment]
We are starting to continue working on the project so if you could make a list of what you have fixed so we don't redo the fix that would be nice.

**Comment by KingGamerXd** [comment]
I will start work on it from tomorrow

**Comment by KingGamerXd** [comment]
I will again fix all bugs from start
