### ISSUE TITLE
Non-unique handler_name when registering packet interceptor

### ISSUE THREAD

**Issue by EvModder** [Exortions/skyblock-2.0#166]
Friendly bug report:

https://github.com/Exortions/skyblock-2.0/blob/da6abefad6f9bd2df49772074d985f84521d8ae4/src/main/java/com/skyblock/skyblock/utilities/sign/SignManager.java#L82
Having `player.getName()` as the name of the handler it is registering in `addBefore()` causes incompatibility with any other plugins whose authors made the same mistake (two plugins trying to register different handlers with the same name).

A good alternative would be to just put a string literal, e.g. `"SignManager"`

I'm currently searching GitHub for other people (besides myself) who fell for this trap due to an incorrect example someone posted on the Bukkit forum which we've all been referencing apparently.

**Comment by Exortions** [comment]
Thank you! Will fix :)
