### ISSUE TITLE
Error Build Faliure

### ISSUE THREAD

**Issue by Ashimbruh** [Exortions/skyblock-2.0#189]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.866 s
[INFO] Finished at: 2024-05-28T07:05:29Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project skyblock: Could not resolve dependencies for project com.skyblock:skyblock:jar:1.0.0: Could not find artifact org.spigotmc:spigot:jar:1.8.8-R0.1-SNAPSHOT in spigotmc-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
~/Soulrise/skyblock-2.0$ 
![error#1](https://github.com/Exortions/skyblock-2.0/assets/149755447/f050c4ee-9d4c-41c4-9f73-3269dcae8572)
![error#2](https://github.com/Exortions/skyblock-2.0/assets/149755447/8a61a5fc-f563-4980-ac63-c834903c0e6b)

**Comment by ghost** [comment]
same here

**Comment by vanshgamerzs** [comment]
same

**Comment by Exortions** [comment]
for all having this issue, update your pom.xml to contain the correct links to the spigot repo and the 1.8.8 jar
