### ISSUE TITLE
use newer spawn/multiple maps

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#25]
Hey there,
while I really liked the old feel of hypixel skyblock, the old spawn does not really resonate with me anymore. I would be really happy if it was replaced (the bazaar does not fit too well into the old map also), or if there was at least an option to choose which version of the spawn chunks to use.
Could this be implemented?
Thanks!

**Comment by Exortions** [comment]
Yeah, the issue is that there is too much currently in Skyblock to implement. We are trying to implement Skyblock *before* dungeons, and once we do that we will update it.

There's just too much to cover, so implementing everything before dungeons will give us a good foundation to do the rest.
