### ISSUE TITLE
randomtickspeed destroys paths

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#29]
![screenshot-20221218-233606](https://user-images.githubusercontent.com/62404294/208322895-d6205885-ed6d-4098-9a8c-00d0f18f33ef.png)

Paths like these slowly turn from dirt into grass due to the randomTickSpeed not being set to 0. The world download used probably has all of these already converted, which is fine for testing, but is hopefully fixed for the future (oh - right - new lobby).

The farms at spawn also suffer from the same problem. They are all destroyed and turned into grass blocks

**Comment by Exortions** [comment]
good point, I'll push the new world in 10 mins.

**Comment by UltraBlackLinux** [comment]
https://www.planetminecraft.com/project/hypixel-skyblock-full-map

this map could be used. Damage already exists here and a sign needs to be removed, but it's by far not as bad as the current map.

**Comment by Exortions** [comment]
Sure, thanks.

**Comment by Exortions** [comment]
what do you mean Damage already exists?

**Comment by Exortions** [comment]
oh you mean path damage? It's okay for now.

**Comment by UltraBlackLinux** [comment]
Found a very thourough map download of teh new hub (spiders den + end + hub + dhub): https://drive.google.com/drive/folders/17zd2jKb-CGGonlBKHHa53Jg2lyF6G_sE

(Most of the mines is missing though, for some reason, but at least the ore sponge exists there, which makes the spawning process easier, I guess)

**Comment by Exortions** [comment]
Yep, we actually have a system for replacing the sponges. I'll use that map soon
