### ISSUE TITLE
disable achievements

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#30]
achievements are still enabled, but really not needed:
![screenshot-20221219-001332](https://user-images.githubusercontent.com/62404294/208324423-0f349c40-bc6a-4bb5-a8a1-1936378bb616.png)

**Comment by Exortions** [comment]
yeah, but you can disable that manually, not worth committing a new world

**Comment by UltraBlackLinux** [comment]
oh I thought that was just a matter of a gamerule, but it is in fact not

**Comment by UltraBlackLinux** [comment]
Oh right. Since you already have gamerule stuff in your init functions why not add that then?

**Comment by Exortions** [comment]
those don't work

**Comment by Exortions** [comment]
gamerules are world based so console executing them does nothing

**Comment by Exortions** [comment]
Actually nvm
