### ISSUE TITLE
damage number armor stands block hits

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#32]
https://chonkyrabbit.eu/files/_bugreports/sb-damage-armorstands.m4v

Somewhat visible

**Comment by Exortions** [comment]
no, it's just that some wolves don't take damage.

This happens when you reload the server and the wolves stay. For some reason this *only* happens with wolves.

**Comment by UltraBlackLinux** [comment]
> no, it's just that some wolves don't take damage.
> 
> This happens when you reload the server and the wolves stay. For some reason this _only_ happens with wolves.

same thing with zombies

**Comment by OptimusChen** [comment]
its an issue with the removeables in the main class

**Comment by Exortions** [comment]
should remove them when `Skyblock#onDisable` is called though? Not sure why it isn't
