### ISSUE TITLE
wolves not automatically aggressive

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#33]
I'm pretty sure that wolves are supposed to be aggressive by default, unlike endermen though.

Currently they are not

**Comment by Exortions** [comment]
No, IIRC that wolves are aggressive after you attack them

**Comment by UltraBlackLinux** [comment]
seems random. some are aggressive, some aren't

**Comment by Exortions** [comment]
it's the same issue as #32.

**Comment by UltraBlackLinux** [comment]
no it's not haha. I'm talking about the default state, not after hitting
