### ISSUE TITLE
warp command requires op

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#40]

**Comment by Exortions** [comment]
no, it requires `skyblock.command.warp`. You can use `/sb help <command>` to get it's description, usages, and permissions.

**Comment by mahfuz6080** [comment]
> no, it requires `skyblock.command.warp`. You can use `/sb help <command>` to get it's description, usages, and permissions.

Have to add perms in pom.xml??

**Comment by UltraBlackLinux** [comment]
you generally use a permission plugin like luckperms to deal with perms

**Comment by mahfuz6080** [comment]
> you generally use a permission plugin like luckperms to deal with perms

Which Perms Should I Give To Default Players Coz There's No Permissions In Pom.xml

Btw can I know your discord
